//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Agenda.cpp
//  @ Date : 16-May-18
//  @ Author : 
//
//


#include "Agenda.h"

Contact* Agenda::SearchContact(string nume_contact) {
}

bool Agenda::AddContact(Contact* info_contact) {
}

bool Agenda::DeleteContact(Contact* info_contact) {
}

list<Contact*> Agenda::ReturnListaContact() {
}

