//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Coleg.h
//  @ Date : 16-May-18
//  @ Author : 
//
//


#if !defined(_COLEG_H)
#define _COLEG_H

#include "Contact.h"

class Coleg : public Contact {
private:
	int nr_telefon;
	string firma;
	string adresa;
};

#endif  //_COLEG_H
