//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Contact.h
//  @ Date : 16-May-18
//  @ Author :
//
//


#if !defined(_CONTACT_H)
#define _CONTACT_H

class Contact {
public:
	void set_nume();
private:
	string nume;
};

#endif  //_CONTACT_H
