//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Contact.cpp
//  @ Date : 16-May-18
//  @ Author : 
//
//


#include "Contact.h"

void Contact::set_nume() {
}

