//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Cunoscut.h
//  @ Date : 16-May-18
//  @ Author : 
//
//


#if !defined(_CUNOSCUT_H)
#define _CUNOSCUT_H

#include "Contact.h"

class Cunoscut : public Contact {
private:
	int nr_telefon;
};

#endif  //_CUNOSCUT_H
