//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Prieten.h
//  @ Date : 16-May-18
//  @ Author : 
//
//


#if !defined(_PRIETEN_H)
#define _PRIETEN_H

#include "Contact.h"

class Prieten : public Contact {
private:
	string data_nastere;
	int nr_telefon;
	string adresa;
};

#endif  //_PRIETEN_H
