//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TipContact.h
//  @ Date : 16-May-18
//  @ Author : 
//
//


#if !defined(_TIPCONTACT_H)
#define _TIPCONTACT_H


enum TipContact {
	PRIETEN,
	COLEG,
	CUNOSCUT
};

#endif  //_TIPCONTACT_H
